### ISSUE TITLE
Clean up old trees

### ISSUE THREAD

**Issue by gbrownmozilla** [mozilla-releng/treestatus#44]
Old trees like mozilla-inbound, esr78 and older are no longer useful and should be removed from the UI. ryanvm and aryx confirmed this today.

Those strings no longer appear in the source code, but remain the UI, even after a successful deployment.

There is a tree deletion UI, but it fails, possibly as reported in #19 . I found an error in Sentry corresponding in time to my tree deletion attempt, 

https://sentry.io/organizations/mozilla/issues/3266114132/?project=6262521&query=is%3Aunresolved
TypeError: kill_trees() missing 1 required positional argument: 'body'
  File "flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 39, in reraise
    raise value
  File "flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "connexion/decorators/validation.py", line 396, in wrapper
    return function(request)
  File "connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "treestatus_api/lib/auth.py", line 181, in wrapper
    return method(*args, **kwargs)

**Comment by gbrownmozilla** [comment]
I think the issue IS #19 and connexion is working appropriately: The treestatus api should not use DELETE with a body. It looks to me like there is an alternate api for deleting a single tree; perhaps we can loop over that api (DELETE /trees/{tree}) instead. (DELETE /trees2 <body>=list of trees should be removed or at least deprecated.)

**Comment by jcristau** [comment]
Treestatus migrated to lando (https://bugzilla.mozilla.org/show_bug.cgi?id=1771695), closing remaining issues on this repo.
